// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { Placeholder, NextImage, Link, Text, useSitecore, CdpHelper, RichText, Image as Image_8a80e63291fea86e0744df19113dc44bec187216 } from '@sitecore-content-sdk/nextjs';
import { useEffect } from 'react';
import React from 'react';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';
import { componentKey, dynamicPlaceholderKey } from '@/lib/component-utils';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'NextImage', value: NextImage },
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'RichText', value: RichText },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: '@/lib/component-utils',
    exports: [
      { name: 'componentKey', value: componentKey },
      { name: 'dynamicPlaceholderKey', value: dynamicPlaceholderKey },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
