---
ID: "acc91730-c602-4746-8449-e1746e61237a"
Parent: "fc60ccb7-5e6b-4a7b-95e1-3eda54447e61"
Template: "fc60ccb7-5e6b-4a7b-95e1-3eda54447e61"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/FeatureIconRow Templates/FeatureIconRow/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
