---
ID: "308c3855-c081-4cd3-9ab8-2036fc69f6ac"
Parent: "2a3e9b50-601a-437b-a2ec-f82b7720f6ac"
Template: "2a3e9b50-601a-437b-a2ec-f82b7720f6ac"
Path: "/sitecore/templates/Project/rai/LinkList/LinkList Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {5A410BE8-B10F-4AB8-8DDB-E2EE833FE2B1}
    {2A3E9B50-601A-437B-A2EC-F82B7720F6AC}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260612T120000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "308c3855-c081-4cd3-9ab8-2036fc69f6ac"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260612T120000Z
