---
ID: "fef9d3c4-4735-4aaa-b9b8-fda20e1a3477"
Parent: "443db055-8dcf-4165-a6e1-c6ca81e1c3f5"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/ProductSolutionPanel Templates/ProductSolutionPanel Folder"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/window_star.png
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{6C4E9E1E-94FF-465D-B7C1-B2EF7697A6F2}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
