---
ID: "09db8d50-9f70-416a-89cd-08dff594a97d"
Parent: "c72efa80-0c2d-4a30-aa6f-3e253ecceb19"
Template: "c72efa80-0c2d-4a30-aa6f-3e253ecceb19"
Path: "/sitecore/templates/Project/miller-homes/ContentCarouselSection/ContentCarouselSection Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260202T110630Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "db67dc79-8838-4f5f-b15b-2ceb7cd35b19"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260202T110630Z
