---
ID: "4f0452b1-d6ae-4b26-ae5e-0d2cca218be7"
Parent: "fe84bf9c-618e-4978-b91a-138e407face4"
Template: "fe84bf9c-618e-4978-b91a-138e407face4"
Path: "/sitecore/templates/Project/british-council/FooterLinkItem Templates/FooterLinkItem/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
