---
ID: "47bbd972-0a9a-4cdc-b91c-e4660c46de58"
Parent: "b50c4168-e3d7-4725-a631-d67da6beb36e"
Template: "b50c4168-e3d7-4725-a631-d67da6beb36e"
Path: "/sitecore/templates/Project/british-council/PortalCarousel Templates/PortalCarousel Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
