---
ID: "2cf2c668-695c-4881-9e8a-81b04d8a8fb1"
Parent: "fcc76945-a2b0-4887-9171-93718a069693"
Template: "fcc76945-a2b0-4887-9171-93718a069693"
Path: "/sitecore/templates/Project/british-council/FeaturedContentSection Templates/FeaturedContentSection/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
