---
ID: "20b83ef4-6a07-4f99-98f4-7743cc135cc1"
Parent: "401e736c-715b-4f1e-8ebe-0f0c25f1acd0"
Template: "401e736c-715b-4f1e-8ebe-0f0c25f1acd0"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/RecommendationCardGrid Templates/RecommendationCardGrid/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
