---
ID: "23da099c-2227-4dce-98c3-7a109eef265a"
Parent: "e47d87ce-5f18-48de-a60c-dac2db566495"
Template: "e47d87ce-5f18-48de-a60c-dac2db566495"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/FaqItem Templates/FaqItem/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
