---
ID: "18156be3-eb02-4480-9b1c-b5e7e0e69836"
Parent: "0938e6f4-ec5f-4f9a-b1f1-9599ade18aca"
Template: "0938e6f4-ec5f-4f9a-b1f1-9599ade18aca"
Path: "/sitecore/templates/Project/bermuda-monetary-authority/RichTextSection Templates/RichTextSection Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
