'use client';
  // This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { useEffect, useMemo, useState, useCallback, useRef, useLayoutEffect, useSyncExternalStore, Fragment as Fragment_9e46adc109100050462083db825547fcdce28feb, createContext, useContext } from 'react';
import Link from 'next/link';
import { Image, Placeholder, Text, useSitecore, RichText, Link as Link_8a80e63291fea86e0744df19113dc44bec187216, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { normalizeSitecoreContentUrl } from '@/lib/kpmg-beyond/fetch-community-content';
import { normalizeCommunityId, getKnownCommunityTitle, resolveCommunityContextFromPathname, canModerateCommunityComments, getCommunityMembershipFromRecord, getCommunityMembershipStatus, isCommunityAdmin, isCommunityMembershipActive, isCommunityOwner, listKnownCommunities, resolveCommunityIdFromMetadataKey } from '@/lib/kpmg-auth0-communities';
import { useEditingHydrationProps } from 'src/components/kpmg/kpmg-editing-hydration';
import { useKpmgBeyondCommunityMembershipMap, useKpmgBeyondJoinedCommunityIds, useKpmgBeyondCommunityMembership, COMMUNITIES_CHANGED_EVENT, dispatchCommunitiesChanged } from 'src/components/kpmg/kpmg-beyond-community-membership';
import { getYourCommunityMembershipStatusLabel, isTrackedYourCommunityMembership, getCommunityListingStatusDisplay, formatCommunityResultsLabel, getCommunityItemsFromFields, matchesCommunitySearch, resolveKpmgBeyondCommunitiesExploreSectionFields } from 'src/components/kpmg/kpmg-beyond-communities-explore-section-shared';
import { KPMG_BEYOND_HOME_COMMUNITIES_FOLDER_ID } from 'src/components/kpmg/KpmgBeyondCommunitiesExploreSection';
import { IconChevronLeft, IconChevronRight, NavIcon, IconPlay, IconBell, IconChevronDown, IconClose, IconMenu, IconSearch, IconUser } from 'src/components/kpmg/kpmg-beyond-icons';
import { categoryMatches, TopPickCategoryFilterContext, useTopPickCategoryFilter } from 'src/components/kpmg/kpmg-beyond-top-picks-context';
import { KpmgBeyondEventListingCardTile } from 'src/components/kpmg/KpmgBeyondEventListingCardTile';
import { extractEventCategoryLabels, filterEventItemsByTab, getEventItemsFromFields, resolveUpcomingOnDemandSectionFields, getSitecoreItemId, resolveMyEventsSectionFields } from 'src/components/kpmg/kpmg-beyond-events-section-shared';
import { parseDroplinkItemId } from '@/lib/kpmg-beyond/parse-droplink';
import { KpmgBeyondArticleCardTile } from 'src/components/kpmg/KpmgBeyondArticleCardTile';
import { extractTopPickCategoryLabels, filterTopPickItemsByTab, folderCardsToTopPickSectionItems, getTopPickItemsFromFields, resolveKpmgBeyondTopPicksSectionFields } from 'src/components/kpmg/kpmg-beyond-top-picks-section-shared';
import { useKpmgBeyondSolutionRouteFields } from 'src/components/kpmg/kpmg-beyond-solution-route-fields';
import { KpmgBeyondSolutionCardTile } from 'src/components/kpmg/KpmgBeyondSolutionCardTile';
import { getSolutionItemsFromFields, matchesSolutionsSearch, resolveKpmgBeyondSolutionsSectionFields } from 'src/components/kpmg/kpmg-beyond-solutions-section-shared';
import { buildLoginUrl } from '@/lib/kpmg-auth0-profile';
import { defaultKpmgBeyondRegisterFields, fieldText, parseMultilineOptions } from 'src/components/kpmg/kpmg-beyond-register-fields';
import { KpmgBeyondProfileFieldLabel, KpmgBeyondProfileSelect, KpmgBeyondProfileSubmitButton, KpmgBeyondProfileTextInput, KpmgBeyondProfileToggle, KpmgBeyondProfileAvatar, KpmgBeyondProfileNavItem, KpmgBeyondProfileReadOnlyValue } from 'src/components/kpmg/KpmgBeyondProfileUi';
import { useUser } from '@auth0/nextjs-auth0/client';
import { buildKpmgAuth0AccountProfile, dummyKpmgAuth0AccountProfile, parseMultilineOptions as parseMultilineOptions_0554ca28cf45970c4d7f08ac070da0ad3f48e022, resolveKpmgAuth0DisplayName } from '@/lib/kpmg-auth0-account';
import { logAuth0ClaimsDebugClient } from '@/lib/auth0-debug';
import { defaultKpmgBeyondProfileSectionFields, fieldText as fieldText_47a5b8d9fcba663aa5b5233bc0e7d77e4a41e473 } from 'src/components/kpmg/kpmg-beyond-profile-fields';
import { createPortal } from 'react-dom';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { Default } from 'src/components/kpmg/KpmgBeyondEventCard';
import { useKpmgBeyondEventSubscription } from 'src/components/kpmg/kpmg-beyond-event-subscription';
import { fileSrc, imageAlt, imageSrc, genericCtaClassName, joinHref, linkText, loginHref, linkHref, fieldText as fieldText_a68e01798457d19567d35246b582e74c8cd6171c } from 'src/components/kpmg/kpmg-beyond-generic-shared';
import { useKpmgBeyondEventPageFields, mapItemToEventCardFields, parseRelatedEventIds, isEventOnDemandFromFields } from 'src/components/kpmg/kpmg-beyond-event-route-fields';
import { resolveSitecoreRouteItemId, normalizeEventId, readSubscribedEventIds } from '@/lib/kpmg-auth0-events';
import { isDiscussionCommentApproved, isDiscussionCommentAuthoredByUser } from '@/lib/kpmg-beyond/discussion-comment-visibility';
import { findDiscussionCommentById, updateDiscussionCommentApproval } from '@/lib/kpmg-beyond/discussion-comment-state';
import { formatDiscussionCommentPublishedDateForDisplay } from '@/lib/kpmg-beyond/discussion-comment-authoring';
import { useKpmgBeyondDiscussionCommunityContext, useKpmgBeyondDiscussionPageFields, useKpmgBeyondDiscussionRouteItemId, useKpmgBeyondCommunityPageFields, useKpmgBeyondCommunityRouteItemId, isCommunityClosed, isCommunityPrivate, isJoinRequestAllowed } from 'src/components/kpmg/kpmg-beyond-community-route-fields';
import { KpmgBeyondCommunityListingCardTile } from 'src/components/kpmg/KpmgBeyondCommunityListingCardTile';
import { isKpmgAuth0AuthenticatedUser } from '@/lib/kpmg-auth0-user';
import { KpmgBeyondProfileMenu } from 'src/components/kpmg/KpmgBeyondProfileMenu';
import { useKpmgBeyondProfileNavigation } from 'src/components/kpmg/kpmg-beyond-profile-nav';
import { useKpmgBeyondArticlePageFields, mapItemToArticleCardFields, parseRelatedArticleIds } from 'src/components/kpmg/kpmg-beyond-article-route-fields';
import { KpmgBeyondArticleListingCardTile } from 'src/components/kpmg/KpmgBeyondArticleListingCardTile';
import { extractArticleTopics, filterArticleItems, getArticleItemsFromFields, resolveKpmgBeyondArticlesSectionFields } from 'src/components/kpmg/kpmg-beyond-articles-section-shared';
import { trackBeyondEventCancellation, trackBeyondEventRegistration } from '@/lib/cdp/cdp-beyond-event-tracking';
import { communityRequiresJoinApproval, isCommunityClosedFromFields, isCommunityPrivateFromFields, isJoinRequestAllowedFromFields } from '@/lib/kpmg-beyond/community-join-approval';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';
import { cn } from '@/shadcn/lib/utils';
import { displayNameFromEmail, EMAIL_REGEX, identifyVisitorByEmail, clearAuth0IdentityMarker, identifyAuth0User } from '@/lib/cdp/cdp-identity';
import dynamic from 'next/dynamic';
import { CdpProfilePanel } from '@/components/cdp-profile-panel/CdpProfilePanel';
import { CdpPageViewTracker } from '@/components/cdp-profile-panel/CdpPageViewTracker';
import { Info, X, ChevronDown, ChevronUp, Copy, Check, Eye, RefreshCw, User, Target, Megaphone, RotateCcw, Loader2 } from 'lucide-react';
import { CdpSubscribeButton } from '@/components/cdp-profile-panel/CdpSubscribeButton';
import { loadCdpGuestProfile } from '@/lib/cdp/cdp-cloud-context';
import { resetSitecoreVisitorSession } from '@/lib/cdp/sitecore-cookie-reset';
import { recordPageView } from '@/lib/cdp/cdp-session-tracker';
import { ensureCloudSdkInitialized } from '@/lib/cdp/cdp-cloud-sdk-init';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'useMemo', value: useMemo },
      { name: 'useState', value: useState },
      { name: 'useCallback', value: useCallback },
      { name: 'useRef', value: useRef },
      { name: 'useLayoutEffect', value: useLayoutEffect },
      { name: 'useSyncExternalStore', value: useSyncExternalStore },
      { name: 'Fragment', value: Fragment_9e46adc109100050462083db825547fcdce28feb },
      { name: 'createContext', value: createContext },
      { name: 'useContext', value: useContext },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Image', value: Image },
      { name: 'Placeholder', value: Placeholder },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'RichText', value: RichText },
      { name: 'Link', value: Link_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: '@/lib/kpmg-beyond/fetch-community-content',
    exports: [
      { name: 'normalizeSitecoreContentUrl', value: normalizeSitecoreContentUrl },
    ]
  },
  {
    module: '@/lib/kpmg-auth0-communities',
    exports: [
      { name: 'normalizeCommunityId', value: normalizeCommunityId },
      { name: 'getKnownCommunityTitle', value: getKnownCommunityTitle },
      { name: 'resolveCommunityContextFromPathname', value: resolveCommunityContextFromPathname },
      { name: 'canModerateCommunityComments', value: canModerateCommunityComments },
      { name: 'getCommunityMembershipFromRecord', value: getCommunityMembershipFromRecord },
      { name: 'getCommunityMembershipStatus', value: getCommunityMembershipStatus },
      { name: 'isCommunityAdmin', value: isCommunityAdmin },
      { name: 'isCommunityMembershipActive', value: isCommunityMembershipActive },
      { name: 'isCommunityOwner', value: isCommunityOwner },
      { name: 'listKnownCommunities', value: listKnownCommunities },
      { name: 'resolveCommunityIdFromMetadataKey', value: resolveCommunityIdFromMetadataKey },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-editing-hydration',
    exports: [
      { name: 'useEditingHydrationProps', value: useEditingHydrationProps },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-community-membership',
    exports: [
      { name: 'useKpmgBeyondCommunityMembershipMap', value: useKpmgBeyondCommunityMembershipMap },
      { name: 'useKpmgBeyondJoinedCommunityIds', value: useKpmgBeyondJoinedCommunityIds },
      { name: 'useKpmgBeyondCommunityMembership', value: useKpmgBeyondCommunityMembership },
      { name: 'COMMUNITIES_CHANGED_EVENT', value: COMMUNITIES_CHANGED_EVENT },
      { name: 'dispatchCommunitiesChanged', value: dispatchCommunitiesChanged },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-communities-explore-section-shared',
    exports: [
      { name: 'getYourCommunityMembershipStatusLabel', value: getYourCommunityMembershipStatusLabel },
      { name: 'isTrackedYourCommunityMembership', value: isTrackedYourCommunityMembership },
      { name: 'getCommunityListingStatusDisplay', value: getCommunityListingStatusDisplay },
      { name: 'formatCommunityResultsLabel', value: formatCommunityResultsLabel },
      { name: 'getCommunityItemsFromFields', value: getCommunityItemsFromFields },
      { name: 'matchesCommunitySearch', value: matchesCommunitySearch },
      { name: 'resolveKpmgBeyondCommunitiesExploreSectionFields', value: resolveKpmgBeyondCommunitiesExploreSectionFields },
    ]
  },
  {
    module: 'src/components/kpmg/KpmgBeyondCommunitiesExploreSection',
    exports: [
      { name: 'KPMG_BEYOND_HOME_COMMUNITIES_FOLDER_ID', value: KPMG_BEYOND_HOME_COMMUNITIES_FOLDER_ID },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-icons',
    exports: [
      { name: 'IconChevronLeft', value: IconChevronLeft },
      { name: 'IconChevronRight', value: IconChevronRight },
      { name: 'NavIcon', value: NavIcon },
      { name: 'IconPlay', value: IconPlay },
      { name: 'IconBell', value: IconBell },
      { name: 'IconChevronDown', value: IconChevronDown },
      { name: 'IconClose', value: IconClose },
      { name: 'IconMenu', value: IconMenu },
      { name: 'IconSearch', value: IconSearch },
      { name: 'IconUser', value: IconUser },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-top-picks-context',
    exports: [
      { name: 'categoryMatches', value: categoryMatches },
      { name: 'TopPickCategoryFilterContext', value: TopPickCategoryFilterContext },
      { name: 'useTopPickCategoryFilter', value: useTopPickCategoryFilter },
    ]
  },
  {
    module: 'src/components/kpmg/KpmgBeyondEventListingCardTile',
    exports: [
      { name: 'KpmgBeyondEventListingCardTile', value: KpmgBeyondEventListingCardTile },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-events-section-shared',
    exports: [
      { name: 'extractEventCategoryLabels', value: extractEventCategoryLabels },
      { name: 'filterEventItemsByTab', value: filterEventItemsByTab },
      { name: 'getEventItemsFromFields', value: getEventItemsFromFields },
      { name: 'resolveUpcomingOnDemandSectionFields', value: resolveUpcomingOnDemandSectionFields },
      { name: 'getSitecoreItemId', value: getSitecoreItemId },
      { name: 'resolveMyEventsSectionFields', value: resolveMyEventsSectionFields },
    ]
  },
  {
    module: '@/lib/kpmg-beyond/parse-droplink',
    exports: [
      { name: 'parseDroplinkItemId', value: parseDroplinkItemId },
    ]
  },
  {
    module: 'src/components/kpmg/KpmgBeyondArticleCardTile',
    exports: [
      { name: 'KpmgBeyondArticleCardTile', value: KpmgBeyondArticleCardTile },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-top-picks-section-shared',
    exports: [
      { name: 'extractTopPickCategoryLabels', value: extractTopPickCategoryLabels },
      { name: 'filterTopPickItemsByTab', value: filterTopPickItemsByTab },
      { name: 'folderCardsToTopPickSectionItems', value: folderCardsToTopPickSectionItems },
      { name: 'getTopPickItemsFromFields', value: getTopPickItemsFromFields },
      { name: 'resolveKpmgBeyondTopPicksSectionFields', value: resolveKpmgBeyondTopPicksSectionFields },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-solution-route-fields',
    exports: [
      { name: 'useKpmgBeyondSolutionRouteFields', value: useKpmgBeyondSolutionRouteFields },
    ]
  },
  {
    module: 'src/components/kpmg/KpmgBeyondSolutionCardTile',
    exports: [
      { name: 'KpmgBeyondSolutionCardTile', value: KpmgBeyondSolutionCardTile },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-solutions-section-shared',
    exports: [
      { name: 'getSolutionItemsFromFields', value: getSolutionItemsFromFields },
      { name: 'matchesSolutionsSearch', value: matchesSolutionsSearch },
      { name: 'resolveKpmgBeyondSolutionsSectionFields', value: resolveKpmgBeyondSolutionsSectionFields },
    ]
  },
  {
    module: '@/lib/kpmg-auth0-profile',
    exports: [
      { name: 'buildLoginUrl', value: buildLoginUrl },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-register-fields',
    exports: [
      { name: 'defaultKpmgBeyondRegisterFields', value: defaultKpmgBeyondRegisterFields },
      { name: 'fieldText', value: fieldText },
      { name: 'parseMultilineOptions', value: parseMultilineOptions },
    ]
  },
  {
    module: 'src/components/kpmg/KpmgBeyondProfileUi',
    exports: [
      { name: 'KpmgBeyondProfileFieldLabel', value: KpmgBeyondProfileFieldLabel },
      { name: 'KpmgBeyondProfileSelect', value: KpmgBeyondProfileSelect },
      { name: 'KpmgBeyondProfileSubmitButton', value: KpmgBeyondProfileSubmitButton },
      { name: 'KpmgBeyondProfileTextInput', value: KpmgBeyondProfileTextInput },
      { name: 'KpmgBeyondProfileToggle', value: KpmgBeyondProfileToggle },
      { name: 'KpmgBeyondProfileAvatar', value: KpmgBeyondProfileAvatar },
      { name: 'KpmgBeyondProfileNavItem', value: KpmgBeyondProfileNavItem },
      { name: 'KpmgBeyondProfileReadOnlyValue', value: KpmgBeyondProfileReadOnlyValue },
    ]
  },
  {
    module: '@auth0/nextjs-auth0/client',
    exports: [
      { name: 'useUser', value: useUser },
    ]
  },
  {
    module: '@/lib/kpmg-auth0-account',
    exports: [
      { name: 'buildKpmgAuth0AccountProfile', value: buildKpmgAuth0AccountProfile },
      { name: 'dummyKpmgAuth0AccountProfile', value: dummyKpmgAuth0AccountProfile },
      { name: 'parseMultilineOptions', value: parseMultilineOptions_0554ca28cf45970c4d7f08ac070da0ad3f48e022 },
      { name: 'resolveKpmgAuth0DisplayName', value: resolveKpmgAuth0DisplayName },
    ]
  },
  {
    module: '@/lib/auth0-debug',
    exports: [
      { name: 'logAuth0ClaimsDebugClient', value: logAuth0ClaimsDebugClient },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-profile-fields',
    exports: [
      { name: 'defaultKpmgBeyondProfileSectionFields', value: defaultKpmgBeyondProfileSectionFields },
      { name: 'fieldText', value: fieldText_47a5b8d9fcba663aa5b5233bc0e7d77e4a41e473 },
    ]
  },
  {
    module: 'react-dom',
    exports: [
      { name: 'createPortal', value: createPortal },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'usePathname', value: usePathname },
      { name: 'useRouter', value: useRouter },
      { name: 'useSearchParams', value: useSearchParams },
    ]
  },
  {
    module: 'src/components/kpmg/KpmgBeyondEventCard',
    exports: [
      { name: 'Default', value: Default },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-event-subscription',
    exports: [
      { name: 'useKpmgBeyondEventSubscription', value: useKpmgBeyondEventSubscription },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-generic-shared',
    exports: [
      { name: 'fileSrc', value: fileSrc },
      { name: 'imageAlt', value: imageAlt },
      { name: 'imageSrc', value: imageSrc },
      { name: 'genericCtaClassName', value: genericCtaClassName },
      { name: 'joinHref', value: joinHref },
      { name: 'linkText', value: linkText },
      { name: 'loginHref', value: loginHref },
      { name: 'linkHref', value: linkHref },
      { name: 'fieldText', value: fieldText_a68e01798457d19567d35246b582e74c8cd6171c },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-event-route-fields',
    exports: [
      { name: 'useKpmgBeyondEventPageFields', value: useKpmgBeyondEventPageFields },
      { name: 'mapItemToEventCardFields', value: mapItemToEventCardFields },
      { name: 'parseRelatedEventIds', value: parseRelatedEventIds },
      { name: 'isEventOnDemandFromFields', value: isEventOnDemandFromFields },
    ]
  },
  {
    module: '@/lib/kpmg-auth0-events',
    exports: [
      { name: 'resolveSitecoreRouteItemId', value: resolveSitecoreRouteItemId },
      { name: 'normalizeEventId', value: normalizeEventId },
      { name: 'readSubscribedEventIds', value: readSubscribedEventIds },
    ]
  },
  {
    module: '@/lib/kpmg-beyond/discussion-comment-visibility',
    exports: [
      { name: 'isDiscussionCommentApproved', value: isDiscussionCommentApproved },
      { name: 'isDiscussionCommentAuthoredByUser', value: isDiscussionCommentAuthoredByUser },
    ]
  },
  {
    module: '@/lib/kpmg-beyond/discussion-comment-state',
    exports: [
      { name: 'findDiscussionCommentById', value: findDiscussionCommentById },
      { name: 'updateDiscussionCommentApproval', value: updateDiscussionCommentApproval },
    ]
  },
  {
    module: '@/lib/kpmg-beyond/discussion-comment-authoring',
    exports: [
      { name: 'formatDiscussionCommentPublishedDateForDisplay', value: formatDiscussionCommentPublishedDateForDisplay },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-community-route-fields',
    exports: [
      { name: 'useKpmgBeyondDiscussionCommunityContext', value: useKpmgBeyondDiscussionCommunityContext },
      { name: 'useKpmgBeyondDiscussionPageFields', value: useKpmgBeyondDiscussionPageFields },
      { name: 'useKpmgBeyondDiscussionRouteItemId', value: useKpmgBeyondDiscussionRouteItemId },
      { name: 'useKpmgBeyondCommunityPageFields', value: useKpmgBeyondCommunityPageFields },
      { name: 'useKpmgBeyondCommunityRouteItemId', value: useKpmgBeyondCommunityRouteItemId },
      { name: 'isCommunityClosed', value: isCommunityClosed },
      { name: 'isCommunityPrivate', value: isCommunityPrivate },
      { name: 'isJoinRequestAllowed', value: isJoinRequestAllowed },
    ]
  },
  {
    module: 'src/components/kpmg/KpmgBeyondCommunityListingCardTile',
    exports: [
      { name: 'KpmgBeyondCommunityListingCardTile', value: KpmgBeyondCommunityListingCardTile },
    ]
  },
  {
    module: '@/lib/kpmg-auth0-user',
    exports: [
      { name: 'isKpmgAuth0AuthenticatedUser', value: isKpmgAuth0AuthenticatedUser },
    ]
  },
  {
    module: 'src/components/kpmg/KpmgBeyondProfileMenu',
    exports: [
      { name: 'KpmgBeyondProfileMenu', value: KpmgBeyondProfileMenu },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-profile-nav',
    exports: [
      { name: 'useKpmgBeyondProfileNavigation', value: useKpmgBeyondProfileNavigation },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-article-route-fields',
    exports: [
      { name: 'useKpmgBeyondArticlePageFields', value: useKpmgBeyondArticlePageFields },
      { name: 'mapItemToArticleCardFields', value: mapItemToArticleCardFields },
      { name: 'parseRelatedArticleIds', value: parseRelatedArticleIds },
    ]
  },
  {
    module: 'src/components/kpmg/KpmgBeyondArticleListingCardTile',
    exports: [
      { name: 'KpmgBeyondArticleListingCardTile', value: KpmgBeyondArticleListingCardTile },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-articles-section-shared',
    exports: [
      { name: 'extractArticleTopics', value: extractArticleTopics },
      { name: 'filterArticleItems', value: filterArticleItems },
      { name: 'getArticleItemsFromFields', value: getArticleItemsFromFields },
      { name: 'resolveKpmgBeyondArticlesSectionFields', value: resolveKpmgBeyondArticlesSectionFields },
    ]
  },
  {
    module: '@/lib/cdp/cdp-beyond-event-tracking',
    exports: [
      { name: 'trackBeyondEventCancellation', value: trackBeyondEventCancellation },
      { name: 'trackBeyondEventRegistration', value: trackBeyondEventRegistration },
    ]
  },
  {
    module: '@/lib/kpmg-beyond/community-join-approval',
    exports: [
      { name: 'communityRequiresJoinApproval', value: communityRequiresJoinApproval },
      { name: 'isCommunityClosedFromFields', value: isCommunityClosedFromFields },
      { name: 'isCommunityPrivateFromFields', value: isCommunityPrivateFromFields },
      { name: 'isJoinRequestAllowedFromFields', value: isJoinRequestAllowedFromFields },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: '@/shadcn/lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: '@/lib/cdp/cdp-identity',
    exports: [
      { name: 'displayNameFromEmail', value: displayNameFromEmail },
      { name: 'EMAIL_REGEX', value: EMAIL_REGEX },
      { name: 'identifyVisitorByEmail', value: identifyVisitorByEmail },
      { name: 'clearAuth0IdentityMarker', value: clearAuth0IdentityMarker },
      { name: 'identifyAuth0User', value: identifyAuth0User },
    ]
  },
  {
    module: 'next/dynamic',
    exports: [
      { name: 'default', value: dynamic },
    ]
  },
  {
    module: '@/components/cdp-profile-panel/CdpProfilePanel',
    exports: [
      { name: 'CdpProfilePanel', value: CdpProfilePanel },
    ]
  },
  {
    module: '@/components/cdp-profile-panel/CdpPageViewTracker',
    exports: [
      { name: 'CdpPageViewTracker', value: CdpPageViewTracker },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'Info', value: Info },
      { name: 'X', value: X },
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'ChevronUp', value: ChevronUp },
      { name: 'Copy', value: Copy },
      { name: 'Check', value: Check },
      { name: 'Eye', value: Eye },
      { name: 'RefreshCw', value: RefreshCw },
      { name: 'User', value: User },
      { name: 'Target', value: Target },
      { name: 'Megaphone', value: Megaphone },
      { name: 'RotateCcw', value: RotateCcw },
      { name: 'Loader2', value: Loader2 },
    ]
  },
  {
    module: '@/components/cdp-profile-panel/CdpSubscribeButton',
    exports: [
      { name: 'CdpSubscribeButton', value: CdpSubscribeButton },
    ]
  },
  {
    module: '@/lib/cdp/cdp-cloud-context',
    exports: [
      { name: 'loadCdpGuestProfile', value: loadCdpGuestProfile },
    ]
  },
  {
    module: '@/lib/cdp/sitecore-cookie-reset',
    exports: [
      { name: 'resetSitecoreVisitorSession', value: resetSitecoreVisitorSession },
    ]
  },
  {
    module: '@/lib/cdp/cdp-session-tracker',
    exports: [
      { name: 'recordPageView', value: recordPageView },
    ]
  },
  {
    module: '@/lib/cdp/cdp-cloud-sdk-init',
    exports: [
      { name: 'ensureCloudSdkInitialized', value: ensureCloudSdkInitialized },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
