// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs } from 'react/jsx-runtime';
import React from 'react';
import { Placeholder, Link, Text } from '@sitecore-content-sdk/nextjs';
import { useEditingHydrationProps } from 'src/components/kpmg/kpmg-editing-hydration';
import { extractCategoryLabels, filterCardsByTab, filterCardsByEventsTab } from '@/lib/kpmg-beyond/fetch-folder-cards';
import { joinMultilineOptions, kpmgBeyondAnnualTurnoverOptions, kpmgBeyondJobRoleOptions, kpmgBeyondSectorOptions } from 'src/components/kpmg/kpmg-beyond-profile-options';
import { kpmgBeyond } from 'src/components/kpmg/kpmg-beyond-tokens';
import { buildLoginUrl } from '@/lib/kpmg-auth0-profile';
import { getSitecoreItemId, normalizeEventId } from '@/lib/kpmg-auth0-events';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-editing-hydration',
    exports: [
      { name: 'useEditingHydrationProps', value: useEditingHydrationProps },
    ]
  },
  {
    module: '@/lib/kpmg-beyond/fetch-folder-cards',
    exports: [
      { name: 'extractCategoryLabels', value: extractCategoryLabels },
      { name: 'filterCardsByTab', value: filterCardsByTab },
      { name: 'filterCardsByEventsTab', value: filterCardsByEventsTab },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-profile-options',
    exports: [
      { name: 'joinMultilineOptions', value: joinMultilineOptions },
      { name: 'kpmgBeyondAnnualTurnoverOptions', value: kpmgBeyondAnnualTurnoverOptions },
      { name: 'kpmgBeyondJobRoleOptions', value: kpmgBeyondJobRoleOptions },
      { name: 'kpmgBeyondSectorOptions', value: kpmgBeyondSectorOptions },
    ]
  },
  {
    module: 'src/components/kpmg/kpmg-beyond-tokens',
    exports: [
      { name: 'kpmgBeyond', value: kpmgBeyond },
    ]
  },
  {
    module: '@/lib/kpmg-auth0-profile',
    exports: [
      { name: 'buildLoginUrl', value: buildLoginUrl },
    ]
  },
  {
    module: '@/lib/kpmg-auth0-events',
    exports: [
      { name: 'getSitecoreItemId', value: getSitecoreItemId },
      { name: 'normalizeEventId', value: normalizeEventId },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
