---
ID: "e13915db-246f-4f72-8318-b95875976de5"
Parent: "4c4cca59-9ce7-4d1c-af02-a5d4cca7f47c"
Template: "4c4cca59-9ce7-4d1c-af02-a5d4cca7f47c"
Path: "/sitecore/templates/Project/rai/EventDetailInfoSection/EventDetailInfoSection Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {BCFAC658-FEEA-4749-9930-F2854112EDC0}
    {4C4CCA59-9CE7-4D1C-AF02-A5D4CCA7F47C}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260612T120000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e13915db-246f-4f72-8318-b95875976de5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260612T120000Z
