---
ID: "e2f3d4c6-4571-4bfe-b290-359a03ad11d7"
Parent: "33e23f7e-27bf-41d2-81da-fd8af504b628"
Template: "33e23f7e-27bf-41d2-81da-fd8af504b628"
Path: "/sitecore/templates/Project/british-council/PortalCarouselPill Templates/PortalCarouselPill/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
