---
ID: "b0f59461-845f-4d03-876f-8835b09f6229"
Parent: "9b98df2c-3f40-43eb-a9eb-93e6c95c38d8"
Template: "9b98df2c-3f40-43eb-a9eb-93e6c95c38d8"
Path: "/sitecore/templates/Project/british-council/SidebarNavigation Templates/SidebarNavigation Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {C9617090-F71D-4BCA-9889-16C8015DB53C}
    {9B98DF2C-3F40-43EB-A9EB-93E6C95C38D8}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
