---
ID: "9e5ae66c-3459-460b-ab0f-3c2e492c6999"
Parent: "095b0eeb-25ed-48aa-860d-02faa5dc0e0c"
Template: "095b0eeb-25ed-48aa-860d-02faa5dc0e0c"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/ProductCardHero Templates/ProductCardHero/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
