---
ID: "83098633-e5e3-4d51-81d5-f150cf2349a5"
Parent: "340670eb-0f92-4377-8820-bda19d4be909"
Template: "340670eb-0f92-4377-8820-bda19d4be909"
Path: "/sitecore/templates/Project/miller-homes/NearbyDevelopmentsSection/NearbyDevelopmentsSection Folder/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /sitecore/shell/themes/standard/Applications/32x32/folder.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {CA4D587A-92A2-4B79-BBC2-4F8546E0E9A4}
    {340670EB-0F92-4377-8820-BDA19D4BE909}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "db4fd677-d7de-41fd-bacd-8f714dca8054"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260202T030039Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6687e9de-d515-43df-80c2-dabf6bdbd9c7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260202T030045Z
