---
ID: "b6ddf55f-990f-4eb6-ab99-91d305210105"
Parent: "6d25a614-e411-4675-b641-58b953587e7e"
Template: "6d25a614-e411-4675-b641-58b953587e7e"
Path: "/sitecore/templates/Project/british-council/ExploreSection Templates/ExploreSection Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
