---
ID: "51c20344-9eb1-45de-9cc4-6467e50cee66"
Parent: "bdc961e3-16bd-46b5-b74c-3ca715d998e4"
Template: "bdc961e3-16bd-46b5-b74c-3ca715d998e4"
Path: "/sitecore/templates/Project/bermuda-monetary-authority/DocumentFilterOption Templates/DocumentFilterOption/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
