---
ID: "b7f2282d-319a-4307-be36-9715a5caf1ea"
Parent: "b6cd7d54-744e-46b6-b189-da4871fd5d70"
Template: "b6cd7d54-744e-46b6-b189-da4871fd5d70"
Path: "/sitecore/templates/Project/british-council/BreadcrumbItem Templates/BreadcrumbItem Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
