---
ID: "6b65c396-a566-4b90-89e1-a72bc2b4534e"
Parent: "a5344580-5b34-4dd7-bfa0-1f3fd3716297"
Template: "a5344580-5b34-4dd7-bfa0-1f3fd3716297"
Path: "/sitecore/templates/Project/miller-homes/ChoiceCard/ChoiceCard Template/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "2229c3a3-96e5-41de-9d5e-7f9cb913303b"
      Hint: CTAText
      Value: Click Here
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260202T004148Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "587855ae-1538-462a-bd73-a7ec2c728fbd"
      Hint: Heading
      Value: |
        I want to register\nfor updates
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1cb77b6c-71bb-4d54-bc32-fe023773030c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260202T004318Z
    - ID: "dab4623e-fe4b-43e7-85e2-717aee86894d"
      Hint: Description
      Value: Receive the latest news, updates and offers from Miller Homes.
    - ID: "ed61057a-05c5-4827-8b20-30cd2a0dfe5b"
      Hint: CTALink
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="_blank" querystring="" id="{6C5F4B85-BF87-4B75-BFA5-5734302B0E77}" />
