---
ID: "1ca9cfd2-9675-47cf-a7fa-079eb0ee6b65"
Parent: "1c5d9049-8064-4d40-b436-52a60c20d407"
Template: "1c5d9049-8064-4d40-b436-52a60c20d407"
Path: "/sitecore/templates/Project/british-council/PortalShell Templates/PortalShell Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
