---
ID: "ec144b84-70bd-4755-85d9-8b5d21827666"
Parent: "02d049fb-5bba-4aad-9ac1-5753ed1aa098"
Template: "02d049fb-5bba-4aad-9ac1-5753ed1aa098"
Path: "/sitecore/templates/Project/bermuda-monetary-authority/TopBar Templates/TopBar/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
