---
ID: "e1891f39-eaed-4dae-b975-a5da1010827c"
Parent: "a2b136db-0f3c-4291-af2e-c30b4c114dd2"
Template: "a2b136db-0f3c-4291-af2e-c30b4c114dd2"
Path: "/sitecore/templates/Project/miller-homes/FeatureSection/FeatureSection Folder/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /sitecore/shell/themes/standard/Applications/32x32/folder.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {65BFA3CC-DD85-4469-A688-72942DBACC78}
    {A2B136DB-0F3C-4291-AF2E-C30B4C114DD2}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c671c239-192e-4347-a83d-c6d67c6ce96e"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260202T005817Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5103d638-d9eb-4dce-b955-10e69f148011"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260202T005823Z
