---
ID: "f9e8c8dc-5270-4123-a04c-42b25c2be1b9"
Parent: "c8b025a9-a9b6-40a9-87eb-8aa591bc0780"
Template: "c8b025a9-a9b6-40a9-87eb-8aa591bc0780"
Path: "/sitecore/templates/Project/miller-homes/NearbyDevelopmentCard/NearbyDevelopmentCard Folder/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /sitecore/shell/themes/standard/Applications/32x32/folder.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {31B96108-EEEE-43E2-BD72-6069E1E33296}
    {C8B025A9-A9B6-40A9-87EB-8AA591BC0780}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "f1a40645-85eb-4702-a95d-44ccdb663900"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260202T143947Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6919937b-c1df-42c5-9d9a-b5b81c34d535"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260202T143959Z
