---
ID: "4e006c29-a8c0-4bd4-833f-d46c0def68a3"
Parent: "d5e5959c-f750-4098-92a7-5abcbd056a10"
Template: "d5e5959c-f750-4098-92a7-5abcbd056a10"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/DigitalFeatureBlock Templates/DigitalFeatureBlock/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
