---
ID: "de317ab6-e9aa-4a5d-9c2e-75d6ac1705e8"
Parent: "34789261-3570-49e8-a5c6-b9aab1e75eaf"
Template: "34789261-3570-49e8-a5c6-b9aab1e75eaf"
Path: "/sitecore/templates/Project/british-council/CollectionBookList Templates/CollectionBookList Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {48DCC401-3767-4E0F-B1BC-B8A0D31084EE}
    {34789261-3570-49E8-A5C6-B9AAB1E75EAF}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
