---
ID: "6ee7c758-8bd9-419f-97cd-00581b8c283d"
Parent: "eb6d19de-c1ac-45e1-83f1-59d14429bfcb"
Template: "eb6d19de-c1ac-45e1-83f1-59d14429bfcb"
Path: /sitecore/templates/Project/kpmg/KPMG Beyond/Main Wrapper/Main Wrapper Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {1848053F-780C-4ED6-B27C-7D21732FF237}
    {EB6D19DE-C1AC-45E1-83F1-59D14429BFCB}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "6e7c217d-9a8e-4f4f-a73e-5465a0aa69c3"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260528T120000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b796bc0c-96d8-428e-8588-8ce155d5ab26"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260529T094712Z
