export const kpmgBeyondJobRoleOptions = [
  'Accountant',
  'Accounts Director',
  'Analyst',
  'Assistant',
  'Assistant Manager',
  'Associate Partner',
  'Audit Director',
  'Chair',
  'Chief Communications Officer',
  'Chief Compliance Officer',
  'Chief Digital Officer',
  'Chief Engineer',
  'Chief Executive Officer',
  'Chief Experience Officer',
  'Chief Finance Officer',
  'Chief Information Officer',
  'Chief Information Security Cyber Officer',
  'Chief Information Security Officer',
  'Chief Legal Officer',
  'Chief Marketing Officer',
  'Chief Operations Officer',
  'Chief Procurement Officer',
  'Chief Risk Officer',
  'Chief Strategy Officer',
  'Chief Technology Officer',
  'Co-founder',
  'Communications Director',
  'Company Secretary',
  'Compliance Director',
  'Creative Director',
  'CSR Director',
  'Deputy Finance Director',
  'Deputy General Counsel',
  'Deputy HR Director',
  'Digital Director',
  'Director',
  'Director (other)',
  'Director of Legal',
  'Director of Tax',
  'Engineering Director',
  'ESG Director',
  'Executive Assistant',
  'Executive Chair',
  'Finance Director',
  'Financial Control Officer',
  'Financial Controller',
  'Founder',
  'General Counsel',
  'Group Chief Technology and Architecture Officer',
  'Group Engineering Director',
  'Group Financial Controller',
  'Group General Counsel',
  'Group Legal Director',
  'Group Senior Project Manager',
  'Group Tax Director',
  'Head of Accounts',
  'Head of Audit',
  'Head of Brand',
  'Head of Change Management',
  'Head of Communications',
  'Head of Compliance',
  'Head of Creative',
  'Head of CSR',
  'Head of Design, Development & Innovation',
  'Head of Digital',
  'Head of ESG',
  'Head of Finance',
  'Head of HR',
  'Head of Information Technology',
  'Head of Innovation',
  'Head of Internal Audit',
  'Head of IT',
  'Head of Learning and Development',
  'Head of Legal',
  'Head of Marketing',
  'Head of Marketing Communications',
  'Head of NPD',
  'Head of Operational Resilience',
  'Head of Operations',
  'Head of Payroll',
  'Head of People',
  'Head of Project Delivery',
  'Head of Recruitment',
  'Head of Research & Development',
  'Head of Risk',
  'Head of Sales',
  'Head of Sales and Marketing',
  'Head of Skills',
  'Head of Strategy',
  'Head of Strategy and Innovation',
  'Head of Talent',
  'Head of Tax',
  'Head of Technical',
  'Head of Technology',
  'Head of Transformation',
  'HR Director',
  'HR Manager',
  'Information Technology Director',
  'Innovation and Digital Construction Manager',
  'Innovation Director',
  'Innovation Manager',
  'Internal Audit Director',
  'Learning and Development Director',
  'Legal Advisor',
  'Legal Manager',
  'Manager',
  'Managing Director',
  'Managing Partner',
  'Marketing Communications Director',
  'Marketing Director',
  'New Product Development Manager',
  'Non Exec Director',
  'Non-Executive Director',
  'Operational Resilience Manager',
  'Operations Director',
  'Owner',
  'Partner',
  'Payroll Director',
  'Payroll Manager',
  'People Director',
  'Principal',
  'Procurement Director',
  'Product and Marketing Director',
  'Product Design Engineer',
  'Production and Procurement Director',
  'Recruitment Director',
  'Research Lead',
  'Sales and Marketing Director',
  'Sales Director',
  'Senior Analyst',
  'Senior Manager',
  'Skills Director',
  'Solicitor',
  'Strategy Director',
  'Sustainability Manager',
  'Sustainability Project Manager',
  'Talent Director',
  'Talent Manager',
  'Tax Director',
  'Tax Manager',
  'Technical Director',
  'Technical Manager',
  'Technology Director',
  'Transformation Director',
  'VAT Manager',
  'Other',
] as const;

export const kpmgBeyondSectorOptions = [
  'Aerospace and defence',
  'Asset Management',
  'Automotive',
  'Banking',
  'Business Services',
  'Central Government',
  'Consumer, retail and leisure',
  'Education',
  'Energy and natural resources',
  'Financial services',
  'Healthcare',
  'Industrial manufacturing',
  'Infrastructure, government and healthcare',
  'Infrastructure, housebuilding and construction',
  'Insurance',
  'Leisure',
  'Life Sciences',
  'Local Government',
  'Media',
  'Mining/Chemicals',
  'Not for profit',
  'Oil and Gas',
  'Police',
  'Power and Utilities',
  'Private Equity',
  'Professional Services',
  'Real Estate',
  'Retail',
  'Social Housing',
  'Technology',
  'Technology, media and telecoms',
  'Telecoms',
  'Transport',
] as const;

export const kpmgBeyondAnnualTurnoverOptions = [
  'Less than £5 million',
  '£5 million - £25 million',
  '£25 million - £50 million',
  '£50 million - £100 million',
  '£100 million - £250 million',
  '£250 million - £500 million',
  'More than £500 million',
] as const;

export function joinMultilineOptions(options: readonly string[]): string {
  return options.join('\n');
}
