---
ID: "67eba3f6-59b0-4df4-ae61-971b684dfcca"
Parent: "07d6eb1a-2746-44ed-aa6f-83e0a41c4c83"
Template: "07d6eb1a-2746-44ed-aa6f-83e0a41c4c83"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/FeatureIconItem Templates/FeatureIconItem/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
