---
ID: "a3c886ac-fe7e-4cbe-a36e-813e08a11702"
Parent: "d61ca05c-6b98-4912-9765-82faa99c5cf0"
Template: "d61ca05c-6b98-4912-9765-82faa99c5cf0"
Path: "/sitecore/templates/Project/british-council/PortalSearchHeader Templates/PortalSearchHeader Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {B50FC809-5FB4-4AE3-A7D7-DB4A6052300E}
    {D61CA05C-6B98-4912-9765-82FAA99C5CF0}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
