---
ID: "75c50fa8-2b4f-40a4-81b9-2c930b3f9a10"
Parent: "6779b510-5ebf-44cb-81a0-bcea223ab53f"
Template: "6779b510-5ebf-44cb-81a0-bcea223ab53f"
Path: "/sitecore/templates/Project/bermuda-monetary-authority/HeroSlide Templates/HeroSlide Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
