---
ID: "a7825c24-e517-4eef-9164-3d8ae9954e13"
Parent: "3fe03997-61fa-4ddf-bacd-9660464087c2"
Template: "3fe03997-61fa-4ddf-bacd-9660464087c2"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/FooterLinkItem Templates/FooterLinkItem Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {5B8B2B17-4F0A-4D92-969B-DA30BFA4D472}
    {3FE03997-61FA-4DDF-BACD-9660464087C2}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
