---
ID: "66894ed4-97f3-43f5-8322-c9be2805b697"
Parent: "82604605-7d25-4147-bd78-e63f9aa2d10f"
Template: "82604605-7d25-4147-bd78-e63f9aa2d10f"
Path: "/sitecore/templates/Project/rai/EventDetailHeroSection/EventDetailHeroSection Template/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "5607b99c-9ff5-431f-85b2-2e461f63c8ff"
      Hint: Title
      Value: Event title
    - ID: "4df04ef6-33cf-4664-aed4-f6b83b5e80da"
      Hint: DateRange
      Value: 1 – 3 June 2026
    - ID: "e09fc5b7-0c5b-4eb5-94b5-3b3f295862ce"
      Hint: Description
      Value: |
        <p>Event description goes here.</p>
    - ID: "8a436096-4fac-40aa-8f48-08ba4cb30381"
      Hint: PrimaryCta
      Value: <link text="Register" linktype="external" url="/" />
    - ID: "9fb6adbf-d43c-466a-80bf-ecce0a7b3dbd"
      Hint: SecondaryCta
      Value: <link text="Add to calendar" linktype="external" url="/" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260612T120000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "66894ed4-97f3-43f5-8322-c9be2805b697"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260612T120000Z
