---
ID: "ef5eff57-a2ef-4a2b-b11a-b67d363ace1d"
Parent: "97acf665-1d92-48b4-a1fc-c87838718ab3"
Template: "97acf665-1d92-48b4-a1fc-c87838718ab3"
Path: /sitecore/templates/Project/kpmg/KPMG Beyond/Event Card/Event Card Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {08185EEF-CACB-44B4-81CB-231122A7B3B5}
    {97ACF665-1D92-48B4-A1FC-C87838718AB3}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "fcd94600-8942-4ed6-b1a0-a2f26c6d6d26"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260528T120000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "baa2b5e4-9364-4014-9c94-1837a3bc38d9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260529T094004Z
