---
ID: "cbf7530a-7ee5-4259-8c21-a1f2f5920027"
Parent: "60484d4f-3463-4531-b7c0-f852d74b9c89"
Template: "60484d4f-3463-4531-b7c0-f852d74b9c89"
Path: /sitecore/templates/Project/kpmg/KPMG Beyond/Top Picks Section/Top Picks Section Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260528T120000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d86ec37c-6cd2-4dc5-8269-cb7d5131b6a1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260528T120000Z
