---
ID: "b4ab83df-50e6-4cd6-8f2d-a7fea94e03e4"
Parent: "0fd85c29-600c-4a89-8cde-cda1ef2b1147"
Template: "0fd85c29-600c-4a89-8cde-cda1ef2b1147"
Path: "/sitecore/templates/Project/british-council/PageTitleHeader Templates/PageTitleHeader/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
