---
ID: "1b3fb407-9656-4ea5-a445-ce956d532564"
Parent: "af753a85-55f3-4547-863e-0caacd68e94f"
Template: "af753a85-55f3-4547-863e-0caacd68e94f"
Path: "/sitecore/templates/Project/bermuda-monetary-authority/PageTitleHeader Templates/PageTitleHeader Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {BB018EF7-15A5-42F7-8751-E1AAE35D8793}
    {AF753A85-55F3-4547-863E-0CAACD68E94F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
