---
ID: "30e82c65-ba98-43c2-bc71-534ae257d5ab"
Parent: "ec10652d-3afd-49be-9b5d-66ee9cbfe063"
Template: "ec10652d-3afd-49be-9b5d-66ee9cbfe063"
Path: "/sitecore/templates/Project/british-council/PortalNavItem Templates/PortalNavItem/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
