---
ID: "b67fcd6a-f324-48cd-a1f5-1ca9d8a8f9a6"
Parent: "6c0ff33e-132f-4ce8-89be-1253930be158"
Template: "6c0ff33e-132f-4ce8-89be-1253930be158"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/InsightsGuidanceSection Templates/InsightsGuidanceSection/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
