---
ID: "983ce432-517e-4a04-865e-4554dca9c227"
Parent: "f05782fa-62b7-46e4-b33b-921e97df5e91"
Template: "f05782fa-62b7-46e4-b33b-921e97df5e91"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/FooterLinkItem Templates/FooterLinkItem Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
