// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, Fragment, jsxs } from 'react/jsx-runtime';
import { Placeholder, CdpHelper, useSitecore, Text, Link, RichText } from '@sitecore-content-sdk/nextjs';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { useEffect, useState, Children, isValidElement, useMemo, createContext, useCallback, useContext } from 'react';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';
import { componentKey, dynamicPlaceholderKey, hasLink, placeholderHasItems } from '@/lib/component-utils';
import { FieldImage } from '@/lib/field-image';
import { DocumentCentreProvider, DocumentCentreResultsPanel, DocumentCentreSidebarControls } from '@/components/bma/DocumentCentreLive';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'Fragment', value: Fragment },
      { name: 'jsxs', value: jsxs },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Text', value: Text },
      { name: 'Link', value: Link },
      { name: 'RichText', value: RichText },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'useState', value: useState },
      { name: 'Children', value: Children },
      { name: 'isValidElement', value: isValidElement },
      { name: 'useMemo', value: useMemo },
      { name: 'createContext', value: createContext },
      { name: 'useCallback', value: useCallback },
      { name: 'useContext', value: useContext },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: '@/lib/component-utils',
    exports: [
      { name: 'componentKey', value: componentKey },
      { name: 'dynamicPlaceholderKey', value: dynamicPlaceholderKey },
      { name: 'hasLink', value: hasLink },
      { name: 'placeholderHasItems', value: placeholderHasItems },
    ]
  },
  {
    module: '@/lib/field-image',
    exports: [
      { name: 'FieldImage', value: FieldImage },
    ]
  },
  {
    module: '@/components/bma/DocumentCentreLive',
    exports: [
      { name: 'DocumentCentreProvider', value: DocumentCentreProvider },
      { name: 'DocumentCentreResultsPanel', value: DocumentCentreResultsPanel },
      { name: 'DocumentCentreSidebarControls', value: DocumentCentreSidebarControls },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
