---
ID: "61c1ef7a-0af9-4953-9030-42ecf3c60068"
Parent: "8debd262-b844-4e3c-badf-98392381285f"
Template: "8debd262-b844-4e3c-badf-98392381285f"
Path: "/sitecore/templates/Project/mea-vertical-demo-banking/QuickActionsGrid Templates/QuickActionsGrid/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
