---
ID: "bb4fbab1-d96b-4213-9fab-a31bec95155f"
Parent: "613ae0d9-2796-426f-be09-9e4d4689448f"
Template: "613ae0d9-2796-426f-be09-9e4d4689448f"
Path: "/sitecore/templates/Project/miller-homes/HouseTypeHeroSection/HouseTypeHeroSection Folder/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /sitecore/shell/themes/standard/Applications/32x32/folder.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {941DB6A8-465D-4DAE-852A-340F39BF56EB}
    {613AE0D9-2796-426F-BE09-9E4D4689448F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "6d580c11-502f-4e2d-8fef-5a8c7e544093"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260202T032003Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2855db93-1381-4bd6-9dab-db625deb1f31"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260202T032032Z
